#!/usr/bin/env bash
# Deploy helper: reads ./cloudflare-worker/.env and sets Wrangler secrets and vars
# Usage: ./deploy_with_env.sh
set -euo pipefail
cd "$(dirname "$0")"
ENV_FILE=".env"
if [[ ! -f "$ENV_FILE" ]]; then
  echo "Error: $ENV_FILE not found in $(pwd)"
  exit 1
fi

# Keys to treat as secrets vs non-secret vars
secret_keys=(WORKER_API_KEY ACCESS_SERVER_API_KEY CLOUDFLARE_API_TOKEN CLOUDFLARE_TOKEN APTOS_PRIVATE_KEY)
vars_keys=(CLOUDFLARE_ZONE_ID ORIGIN_URL PAYMENT_ADDRESS PRICE_AMOUNT PRICE_CURRENCY ACCESS_SERVER_URL BOT_PAYMENT_SYSTEM_URL API_BASE_URL API_URL)

# helpers
trim() {
  local s="$1"
  # remove leading/trailing whitespace
  s="$(echo "$s" | sed 's/^\s*//;s/\s*$//')"
  printf '%s' "$s"
}

in_array() {
  local val="$1"; shift
  local arr
  for arr in "$@"; do
    if [[ "$arr" == "$val" ]]; then
      return 0
    fi
  done
  return 1
}

any_vars=0
secrets_set=0

# Read file line-by-line to set secrets and detect presence of vars. We won't rely on associative arrays.
while IFS= read -r line || [[ -n "$line" ]]; do
  line="$(trim "$line")"
  [[ -z "$line" ]] && continue
  [[ "$line" =~ ^# ]] && continue

  if [[ "$line" =~ ^export[[:space:]]+ ]]; then
    line="${line#export }"
  fi

  if [[ "$line" != *=* ]]; then
    continue
  fi
  key="${line%%=*}"
  val="${line#*=}"
  key="$(trim "$key")"

  # strip surrounding quotes from val (simple)
  val="$(trim "$val")"
  if [[ ("$val" == '"'*'"') || ("$val" == "'"*"'") ]]; then
    val="${val#\"}"
    val="${val%\"}"
    val="${val#\'}"
    val="${val%\'}"
  fi

  if in_array "$key" "${secret_keys[@]}"; then
    if [[ -n "$val" ]]; then
      echo "Setting secret: $key"
      printf '%s' "$val" | npx wrangler secret put "$key"
      secrets_set=$((secrets_set+1))
    else
      echo "Skipping empty secret: $key"
    fi
  elif in_array "$key" "${vars_keys[@]}"; then
    any_vars=1
  else
    echo "Ignoring .env key not in secret/vars lists: $key"
  fi

done < "$ENV_FILE"

# Build vars_block by extracting the last assignment for each key from the ENV_FILE (portable)
vars_block="[vars]\n"
if [[ "$any_vars" -eq 1 ]]; then
  for k in "${vars_keys[@]}"; do
    # Use awk to get the last matching line for the key (handles spaces around key and equals)
    val=$(awk -F'=' -v key="$k" '
      BEGIN{res=""}
      {
        line=$0
        if(match(line, "^\\s*" key "\\s*=")){
          sub("^\\s*" key "\\s*=","",line)
          res=line
        }
      }
      END{
        # trim
        gsub(/^[ \t]+|[ \t]+$/,"",res)
        # remove surrounding quotes
        if(res ~ /^".*"$/){ sub(/"/,"",res); sub(/"$/,"",res) }
        if(res ~ /^\'.*\'$/){ sub("'","",res); sub("'$/","",res) }
        if(res != "") print res
      }
    ' "$ENV_FILE" || true)

    if [[ -n "$val" ]]; then
      # Escape backslashes and double quotes for TOML
      escaped_val="$(printf '%s' "$val" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g')"
      vars_block+="$k = \"$escaped_val\"\n"
    fi
  done
fi

if [[ "$any_vars" -eq 1 ]]; then
  TOML_FILE="wrangler.toml"
  BACKUP_FILE="wrangler.toml.bak"
  if [[ -f "$TOML_FILE" ]]; then
    echo "Backing up $TOML_FILE -> $BACKUP_FILE"
    cp "$TOML_FILE" "$BACKUP_FILE"

    # Remove existing [vars] section from TOML (from [vars] until next section header starting with [)
    awk '
      BEGIN{skip=0}
      {
        if(skip){
          if(/^[[]/){ skip=0; print }
          else next
        } else {
          if(/^\[vars\]/){ skip=1; next }
          else print
        }
      }
    ' "$TOML_FILE" > "$TOML_FILE.tmp"

    # Remove any existing assignments for the vars we will write (prevent duplicate keys)
    for key in "${vars_keys[@]}"; do
      sed -i.bak "/^${key}[[:space:]]*=.*/d" "$TOML_FILE.tmp" || true
      rm -f "$TOML_FILE.tmp.bak" || true
    done

  else
    echo "No existing $TOML_FILE found; creating a new one."
    printf "# Generated by deploy_with_env.sh\n" > "$TOML_FILE.tmp"
  fi

  # Append the generated vars_block
  printf "\n# Generated by deploy_with_env.sh\n" >> "$TOML_FILE.tmp"
  printf "%b\n" "$vars_block" >> "$TOML_FILE.tmp"

  mv "$TOML_FILE.tmp" "$TOML_FILE"
  echo "Updated $TOML_FILE with [vars] from $ENV_FILE"
else
  echo "No non-secret vars found to write to wrangler.toml"
fi

# Summary and deploy
echo "Secrets set: $secrets_set"
if [[ "$secrets_set" -eq 0 ]]; then
  echo "Warning: No secrets were set. If you expected secrets from $ENV_FILE, ensure keys are present and listed in secret_keys." >&2
fi

echo "Running: npx wrangler deploy"
npx wrangler deploy

echo "Deployment complete. Remember: secrets were set using wrangler secret put; verify in Cloudflare Dashboard if needed."
