/**
 * Gatekeeper Types
 * Type definitions for the bot firewall protection system
 */

// Project type is now generated by Prisma - see @prisma/client

export interface CloudflareZoneResponse {
  success: boolean;
  result?: {
    id: string;
    name: string;
    nameservers: string[];
    status: string;
  };
  errors?: Array<{
    code: number;
    message: string;
  }>;
}

export interface CloudflareZoneStatusResponse {
  success: boolean;
  result?: {
    id: string;
    name: string;
    status: string;
    nameservers: string[];
  };
  errors?: Array<{
    code: number;
    message: string;
  }>;
}

export interface WAFSkipRule {
  description: string;
  expression: string;
  action: 'skip';
  action_parameters: {
    ruleset: 'current';
    phases: string[];
  };
  enabled: boolean;
}

export interface WAFRulesetResponse {
  success: boolean;
  result?: {
    id: string;
    rules: WAFSkipRule[];
  };
  errors?: Array<{
    code: number;
    message: string;
  }>;
}

export interface RegisterDomainResponse {
  success: boolean;
  zone_id?: string;
  nameservers?: string[];
  secret_key?: string;
  error?: string;
}

export interface VerifyAndConfigureResponse {
  status: 'success' | 'pending' | 'error';
  message: string;
  protected?: boolean;
}

// ProjectWithoutSecretKey type removed - use Prisma Project type directly
